bugfix delete_char empty range for randrange
Could get
Traceback (most recent call last):
  File "...blackbox.py", line 480, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File ".../blackbox.py", line 354, in main
    result = mutator(seed)
             ^^^^^^^^^^^^^
  File ".../Fuzz3/mutators.py", line 99, in delete_char
    i = random.randrange(1, len(data) - 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Python/Python-3.11.5/lib/python3.11/random.py", line 345, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1, 1, 0)

I think this was due to short seeds (ie <=2 chars) causing randrange to fail